/* Keep the service worker's club list in step with the club decks.
 *
 *     node _tools/sw-clubs.js
 *
 * The six league team pickers draw a crest per club, and a crest that is not
 * precached is a grey box on a phone with no signal. There are 114 of them and
 * they change every time a club goes up or down, so the list is GENERATED
 * between two markers in sw.js rather than maintained by hand. Run this after
 * every build-clubs.js run.
 *
 * It also bumps CACHE, because a precache list that changed and a cache name
 * that did not is the single most confusing thing that can happen in this repo:
 * the code is right, the tests are green, and the phone keeps showing you
 * yesterday.
 */
const fs = require("fs");
const path = require("path");

const REPO = path.join(__dirname, "..");
const SW = path.join(REPO, "sw.js");
const DIRS = ["premier", "laliga", "bundesliga", "seriea", "belgian", "eredivisie"];
const OPEN = "/* ---- CLUBS: generated by _tools/sw-clubs.js, do not edit by hand ---- */";
const SHUT = "/* ---- end of the generated club list ---- */";

const decks = [];
const crests = new Set();
let clubs = 0;
for (const d of DIRS) {
  const f = path.join(REPO, "assets", d, "clubs.json");
  if (!fs.existsSync(f)) { console.log("  no deck yet for " + d + ", skipped"); continue; }
  decks.push("assets/" + d + "/clubs.json");
  /* the question decks go in the same list: a league that has its clubs
     precached and not its questions is a team picker that opens onto nothing */
  for (const also of ["index.json", "mc.json"]) {
    if (fs.existsSync(path.join(REPO, "assets", d, also))) decks.push("assets/" + d + "/" + also);
  }
  const rows = JSON.parse(fs.readFileSync(f, "utf8"));
  for (const name of Object.keys(rows)) {
    clubs++;
    const slug = rows[name].flag;
    if (slug) crests.add("assets/logos/" + slug + ".png");
  }
}
const missing = [...crests].filter(p => !fs.existsSync(path.join(REPO, p)));
if (missing.length) {
  console.error("NOT WRITING. " + missing.length + " crest file(s) named by a deck are not on disk:");
  missing.slice(0, 10).forEach(p => console.error("  " + p));
  process.exit(1);
}

const block = [
  OPEN,
  "const CLUB_DECKS = " + JSON.stringify(decks) + ";",
  "const CLUB_CRESTS = " + JSON.stringify([...crests].sort()) + ";",
  SHUT,
].join("\n");

let s = fs.readFileSync(SW, "utf8");
const nl = s.includes("\r\n") ? "\r\n" : "\n";
const a = s.indexOf(OPEN), b = s.indexOf(SHUT);
if (a >= 0 && b > a) {
  s = s.slice(0, a) + block.split("\n").join(nl) + s.slice(b + SHUT.length);
} else {
  /* first run: drop it in above the precache list that will use it */
  const anchor = "const EXTRA_ASSETS";
  const at = s.indexOf(anchor);
  if (at < 0) { console.error("cannot find EXTRA_ASSETS to sit above"); process.exit(1); }
  s = s.slice(0, at) + block.split("\n").join(nl) + nl + s.slice(at);
}

/* bump the cache, or phones keep serving the old build */
const m = s.match(/const CACHE = "ball-quiz-2-v(\d+)"/);
if (m) {
  const next = Number(m[1]) + 1;
  s = s.replace(m[0], 'const CACHE = "ball-quiz-2-v' + next + '"');
  console.log("CACHE bumped to v" + next);
}
fs.writeFileSync(SW, s);
console.log("wrote " + decks.length + " decks and " + crests.size + " crests for " + clubs + " clubs");
